# Generated by Django 4.1 on 2022-08-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leagues",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "leagues",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pokedex",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("num", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "pokedex",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rankings",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "rankings",
                "managed": False,
            },
        ),
    ]
