# Generated by Django 4.1 on 2022-08-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokedex",
            options={"managed": True},
        ),
    ]
