# Generated by Django 4.1 on 2022-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_pokedex_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedex",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
